print('Seja Bem Vindo Onii-chan')
a = input('Digite algo:')
print(a.isnumeric())
print(a.isalpha())
print(a.isdecimal())
print(a.isdigit())
print(a.islower())
print(a.isnumeric())
print(a.isspace())
print(a.isalnum())